apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lbh54izq3-python 
  janus-idp.io/tekton: lbh54izq3-python
  backstage.io/kubernetes-id: lbh54izq3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lbh54izq3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml