apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lbh54izq3-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lbh54izq3-python 
  name: lbh54izq3-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lbh54izq3-python 
